import {
  Club,
  Player,
  LegendPlayer,
  StandingRow,
  TransferListing,
  LedgerItem,
} from './types.js';

export const INITIAL_CLUB: Club = {
  id: 'c1',
  name: 'Real Madrid',
  shortCode: 'RMA',
  slug: 'real-madrid',
  reputation: 92,
  balanceEur: 250_000_000,
  stadiumCapacity: 81044,
};

export const INITIAL_SQUAD: Player[] = [
  {
    id: 'p1',
    fullName: 'Thibaut Courtois',
    primaryPosition: 'GK',
    overallRating: 89,
    marketValueEur: 45_000_000,
    nationality: 'Belgium',
    isStarting: true,
    pitchX: 50,
    pitchY: 88,
    attributes: {
      pace: 46,
      shooting: 18,
      passing: 31,
      dribbling: 50,
      defending: 19,
      physical: 82,
    },
  },
  {
    id: 'p2',
    fullName: 'Dani Carvajal',
    primaryPosition: 'RB',
    overallRating: 85,
    marketValueEur: 12_000_000,
    nationality: 'Spain',
    isStarting: true,
    pitchX: 85,
    pitchY: 68,
    attributes: {
      pace: 80,
      shooting: 54,
      passing: 78,
      dribbling: 79,
      defending: 83,
      physical: 81,
    },
  },
  {
    id: 'p3',
    fullName: 'Éder Militão',
    primaryPosition: 'CB',
    overallRating: 85,
    marketValueEur: 60_000_000,
    nationality: 'Brazil',
    isStarting: true,
    pitchX: 62,
    pitchY: 72,
    attributes: {
      pace: 82,
      shooting: 50,
      passing: 68,
      dribbling: 71,
      defending: 85,
      physical: 84,
    },
  },
  {
    id: 'p4',
    fullName: 'Antonio Rüdiger',
    primaryPosition: 'CB',
    overallRating: 87,
    marketValueEur: 25_000_000,
    nationality: 'Germany',
    isStarting: true,
    pitchX: 38,
    pitchY: 72,
    attributes: {
      pace: 82,
      shooting: 53,
      passing: 71,
      dribbling: 67,
      defending: 86,
      physical: 86,
    },
  },
  {
    id: 'p5',
    fullName: 'Ferland Mendy',
    primaryPosition: 'LB',
    overallRating: 83,
    marketValueEur: 22_000_000,
    nationality: 'France',
    isStarting: true,
    pitchX: 15,
    pitchY: 68,
    attributes: {
      pace: 88,
      shooting: 62,
      passing: 74,
      dribbling: 78,
      defending: 80,
      physical: 84,
    },
  },
  {
    id: 'p6',
    fullName: 'Federico Valverde',
    primaryPosition: 'CM',
    overallRating: 88,
    marketValueEur: 120_000_000,
    nationality: 'Uruguay',
    isStarting: true,
    pitchX: 65,
    pitchY: 45,
    attributes: {
      pace: 87,
      shooting: 82,
      passing: 84,
      dribbling: 84,
      defending: 80,
      physical: 85,
    },
  },
  {
    id: 'p7',
    fullName: 'Jude Bellingham',
    primaryPosition: 'CAM',
    overallRating: 90,
    marketValueEur: 180_000_000,
    nationality: 'England',
    isStarting: true,
    pitchX: 50,
    pitchY: 35,
    attributes: {
      pace: 80,
      shooting: 86,
      passing: 84,
      dribbling: 88,
      defending: 78,
      physical: 85,
    },
  },
  {
    id: 'p8',
    fullName: 'Aurélien Tchouaméni',
    primaryPosition: 'CDM',
    overallRating: 85,
    marketValueEur: 90_000_000,
    nationality: 'France',
    isStarting: true,
    pitchX: 35,
    pitchY: 45,
    attributes: {
      pace: 74,
      shooting: 69,
      passing: 79,
      dribbling: 77,
      defending: 83,
      physical: 84,
    },
  },
  {
    id: 'p9',
    fullName: 'Rodrygo',
    primaryPosition: 'RW',
    overallRating: 86,
    marketValueEur: 110_000_000,
    nationality: 'Brazil',
    isStarting: true,
    pitchX: 82,
    pitchY: 18,
    attributes: {
      pace: 89,
      shooting: 81,
      passing: 79,
      dribbling: 87,
      defending: 32,
      physical: 62,
    },
  },
  {
    id: 'p10',
    fullName: 'Kylian Mbappé',
    primaryPosition: 'ST',
    overallRating: 91,
    marketValueEur: 180_000_000,
    nationality: 'France',
    isStarting: true,
    pitchX: 50,
    pitchY: 14,
    attributes: {
      pace: 97,
      shooting: 90,
      passing: 80,
      dribbling: 92,
      defending: 36,
      physical: 78,
    },
  },
  {
    id: 'p11',
    fullName: 'Vinícius Júnior',
    primaryPosition: 'LW',
    overallRating: 90,
    marketValueEur: 200_000_000,
    nationality: 'Brazil',
    isStarting: true,
    pitchX: 18,
    pitchY: 18,
    attributes: {
      pace: 95,
      shooting: 84,
      passing: 81,
      dribbling: 91,
      defending: 29,
      physical: 69,
    },
  },
  {
    id: 'p12',
    fullName: 'Luka Modrić',
    primaryPosition: 'CM',
    overallRating: 86,
    marketValueEur: 6_000_000,
    nationality: 'Croatia',
    isStarting: false,
    attributes: {
      pace: 62,
      shooting: 76,
      passing: 89,
      dribbling: 86,
      defending: 72,
      physical: 64,
    },
  },
  {
    id: 'p13',
    fullName: 'Eduardo Camavinga',
    primaryPosition: 'CM',
    overallRating: 84,
    marketValueEur: 100_000_000,
    nationality: 'France',
    isStarting: false,
    attributes: {
      pace: 80,
      shooting: 67,
      passing: 80,
      dribbling: 84,
      defending: 81,
      physical: 80,
    },
  },
  {
    id: 'p14',
    fullName: 'Brahim Díaz',
    primaryPosition: 'CAM',
    overallRating: 82,
    marketValueEur: 40_000_000,
    nationality: 'Morocco',
    isStarting: false,
    attributes: {
      pace: 85,
      shooting: 74,
      passing: 78,
      dribbling: 85,
      defending: 31,
      physical: 56,
    },
  },
  {
    id: 'p15',
    fullName: 'Arda Güler',
    primaryPosition: 'CAM',
    overallRating: 78,
    marketValueEur: 45_000_000,
    nationality: 'Turkey',
    isStarting: false,
    attributes: {
      pace: 74,
      shooting: 76,
      passing: 81,
      dribbling: 83,
      defending: 45,
      physical: 58,
    },
  },
  {
    id: 'p16',
    fullName: 'Endrick',
    primaryPosition: 'ST',
    overallRating: 77,
    marketValueEur: 60_000_000,
    nationality: 'Brazil',
    isStarting: false,
    attributes: {
      pace: 89,
      shooting: 78,
      passing: 62,
      dribbling: 80,
      defending: 30,
      physical: 78,
    },
  },
  {
    id: 'p17',
    fullName: 'Andriy Lunin',
    primaryPosition: 'GK',
    overallRating: 81,
    marketValueEur: 25_000_000,
    nationality: 'Ukraine',
    isStarting: false,
    attributes: {
      pace: 48,
      shooting: 15,
      passing: 35,
      dribbling: 45,
      defending: 18,
      physical: 76,
    },
  },
  {
    id: 'p18',
    fullName: 'Lucas Vázquez',
    primaryPosition: 'RB',
    overallRating: 79,
    marketValueEur: 4_000_000,
    nationality: 'Spain',
    isStarting: false,
    attributes: {
      pace: 78,
      shooting: 72,
      passing: 77,
      dribbling: 79,
      defending: 73,
      physical: 72,
    },
  },
];

export const INITIAL_STANDINGS: StandingRow[] = [
  {
    position: 1,
    clubName: 'Real Madrid',
    shortCode: 'RMA',
    played: 5,
    won: 4,
    drawn: 1,
    lost: 0,
    goalsFor: 12,
    goalsAgainst: 3,
    goalDifference: 9,
    points: 13,
  },
  {
    position: 2,
    clubName: 'FC Barcelona',
    shortCode: 'BAR',
    played: 5,
    won: 4,
    drawn: 0,
    lost: 1,
    goalsFor: 11,
    goalsAgainst: 4,
    goalDifference: 7,
    points: 12,
  },
  {
    position: 3,
    clubName: 'Manchester City',
    shortCode: 'MCI',
    played: 5,
    won: 3,
    drawn: 2,
    lost: 0,
    goalsFor: 10,
    goalsAgainst: 4,
    goalDifference: 6,
    points: 11,
  },
  {
    position: 4,
    clubName: 'Bayern München',
    shortCode: 'BAY',
    played: 5,
    won: 3,
    drawn: 1,
    lost: 1,
    goalsFor: 9,
    goalsAgainst: 5,
    goalDifference: 4,
    points: 10,
  },
  {
    position: 5,
    clubName: 'Arsenal',
    shortCode: 'ARS',
    played: 5,
    won: 3,
    drawn: 0,
    lost: 2,
    goalsFor: 8,
    goalsAgainst: 6,
    goalDifference: 2,
    points: 9,
  },
  {
    position: 6,
    clubName: 'Paris Saint-Germain',
    shortCode: 'PSG',
    played: 5,
    won: 2,
    drawn: 2,
    lost: 1,
    goalsFor: 7,
    goalsAgainst: 6,
    goalDifference: 1,
    points: 8,
  },
  {
    position: 7,
    clubName: 'Liverpool',
    shortCode: 'LIV',
    played: 5,
    won: 2,
    drawn: 1,
    lost: 2,
    goalsFor: 6,
    goalsAgainst: 7,
    goalDifference: -1,
    points: 7,
  },
  {
    position: 8,
    clubName: 'Inter Milan',
    shortCode: 'INT',
    played: 5,
    won: 2,
    drawn: 0,
    lost: 3,
    goalsFor: 5,
    goalsAgainst: 8,
    goalDifference: -3,
    points: 6,
  },
];

export const LEGEND_MARKET: LegendPlayer[] = [
  {
    id: 'leg-1',
    fullName: 'Cristiano Ronaldo (Prime)',
    era: '2011/12 Peak Real Madrid',
    primaryPosition: 'ST',
    overallRating: 95,
    priceEur: 500_000_000,
    nationality: 'Portugal',
    attributes: {
      pace: 94,
      shooting: 96,
      passing: 84,
      dribbling: 92,
      defending: 38,
      physical: 89,
    },
  },
  {
    id: 'leg-2',
    fullName: 'Lionel Messi (Prime)',
    era: '2011/12 91-Goal Record Year',
    primaryPosition: 'RW',
    overallRating: 96,
    priceEur: 500_000_000,
    nationality: 'Argentina',
    attributes: {
      pace: 93,
      shooting: 95,
      passing: 94,
      dribbling: 98,
      defending: 35,
      physical: 72,
    },
  },
  {
    id: 'leg-3',
    fullName: 'Zinedine Zidane',
    era: '2001/02 Champions League Winner',
    primaryPosition: 'CAM',
    overallRating: 94,
    priceEur: 400_000_000,
    nationality: 'France',
    attributes: {
      pace: 78,
      shooting: 86,
      passing: 95,
      dribbling: 95,
      defending: 68,
      physical: 84,
    },
  },
  {
    id: 'leg-4',
    fullName: 'Ronaldo Nazário (R9)',
    era: "1997/98 Ballon d'Or Peak",
    primaryPosition: 'ST',
    overallRating: 94,
    priceEur: 450_000_000,
    nationality: 'Brazil',
    attributes: {
      pace: 96,
      shooting: 94,
      passing: 79,
      dribbling: 95,
      defending: 32,
      physical: 85,
    },
  },
  {
    id: 'leg-5',
    fullName: 'Paolo Maldini',
    era: '2002/03 Champions League Captain',
    primaryPosition: 'CB',
    overallRating: 94,
    priceEur: 350_000_000,
    nationality: 'Italy',
    attributes: {
      pace: 86,
      shooting: 56,
      passing: 76,
      dribbling: 74,
      defending: 97,
      physical: 88,
    },
  },
  {
    id: 'leg-6',
    fullName: 'Ronaldinho Gaucho',
    era: "2005/06 Ballon d'Or Magic",
    primaryPosition: 'LW',
    overallRating: 93,
    priceEur: 380_000_000,
    nationality: 'Brazil',
    attributes: {
      pace: 90,
      shooting: 88,
      passing: 90,
      dribbling: 97,
      defending: 36,
      physical: 79,
    },
  },
  {
    id: 'leg-7',
    fullName: 'Thierry Henry',
    era: '2003/04 Invincibles Leader',
    primaryPosition: 'ST',
    overallRating: 93,
    priceEur: 360_000_000,
    nationality: 'France',
    attributes: {
      pace: 94,
      shooting: 91,
      passing: 83,
      dribbling: 90,
      defending: 40,
      physical: 80,
    },
  },
  {
    id: 'leg-8',
    fullName: 'Xavi Hernández',
    era: '2010/11 Tiki-Taka Mastermind',
    primaryPosition: 'CM',
    overallRating: 92,
    priceEur: 300_000_000,
    nationality: 'Spain',
    attributes: {
      pace: 72,
      shooting: 74,
      passing: 96,
      dribbling: 92,
      defending: 72,
      physical: 68,
    },
  },
  {
    id: 'leg-9',
    fullName: 'Iker Casillas',
    era: '2010 World Cup & UCL Legend',
    primaryPosition: 'GK',
    overallRating: 92,
    priceEur: 280_000_000,
    nationality: 'Spain',
    attributes: {
      pace: 65,
      shooting: 20,
      passing: 50,
      dribbling: 55,
      defending: 25,
      physical: 84,
    },
  },
];

export const INITIAL_TRANSFERS: TransferListing[] = [
  {
    id: 'tr-101',
    playerName: 'Lamine Yamal',
    position: 'RW',
    overallRating: 84,
    priceEur: 120_000_000,
    sellerClubName: 'FC Barcelona',
    listedAt: '1 soat oldin',
  },
  {
    id: 'tr-102',
    playerName: 'Erling Haaland',
    position: 'ST',
    overallRating: 91,
    priceEur: 200_000_000,
    sellerClubName: 'Manchester City',
    listedAt: '3 soat oldin',
  },
  {
    id: 'tr-103',
    playerName: 'Florian Wirtz',
    position: 'CAM',
    overallRating: 87,
    priceEur: 110_000_000,
    sellerClubName: 'Bayer Leverkusen',
    listedAt: '5 soat oldin',
  },
  {
    id: 'tr-104',
    playerName: 'Jamal Musiala',
    position: 'CAM',
    overallRating: 88,
    priceEur: 130_000_000,
    sellerClubName: 'Bayern München',
    listedAt: '8 soat oldin',
  },
];

export const INITIAL_FINANCES: LedgerItem[] = [
  {
    id: 'fin-1',
    type: 'SPONSORSHIP_INCOME',
    description: 'Tur uchun homiylik daromadi',
    amountEur: 2500000,
    date: 'Bugun 18:30',
  },
  {
    id: 'fin-2',
    type: 'MATCH_WIN_BONUS',
    description: 'G‘alaba bonusi (Tur 5: Real Madrid 3 - 1 Arsenal)',
    amountEur: 1500000,
    date: 'Bugun 18:00',
  },
  {
    id: 'fin-3',
    type: 'STADIUM_INCOME',
    description: 'Chipta va stadion daromadlari (Bernabéu)',
    amountEur: 1500000,
    date: 'Bugun 18:00',
  },
  {
    id: 'fin-4',
    type: 'TRANSFER_SALE',
    description: 'Futbolchi sotuvi: Dani Ceballos',
    amountEur: 18000000,
    date: 'Kecha 14:15',
  },
];
